= Game of Thrones: Houses
:csv-url: https://raw.githubusercontent.com/mneedham/neo4j-got/master/data/import/
:icons: font

== Importing houses

In this next section we're going to import the houses that characters belong to.

Run the following query to explore the houses CSV file:

[source, cypher,subs=attributes]
----
LOAD CSV WITH HEADERS FROM "{csv-url}houses.csv" AS row
RETURN row
----

Now let's create a node with the `House` label for each row in the file:

[source, cypher,subs=attributes]
----
LOAD CSV WITH HEADERS FROM "{csv-url}houses.csv" AS row
MERGE (house:House {id: row.link})
ON CREATE SET house.name = row.name
----

Run the following query to return all the houses:

[source, cypher]
----
MATCH (house:House)
RETURN house
----

You should see 73 nodes if the import has worked as expected. 

= Exercise: Create allegiances

Now it's your turn!
Run the following query to view the allegiances between characters and houses:

[source, cypher,subs=attributes]
----
LOAD CSV WITH HEADERS FROM "{csv-url}allegiances.csv" AS row
RETURN row.character, row.house
----

= Answer: Create allegiances

Create a `HAS_ALLEGIANCE_TO` relationship for each character/house pair in the file.

[source, cypher]
----
MATCH (house:House)
RETURN house
----

[source, cypher, subs = attributes]
----
LOAD CSV WITH HEADERS FROM "{csv-url}allegiances.csv" AS row
RETURN row
ORDER BY rand()
LIMIT 10
----

If you run this query a few times you'll see that it includes lots of allegiances, not just ones between characters and houses.
Are we gonna import those as well?

For now we're going to filter those rows to only find allegiances between characters and houses.
<This sentence is repetitive with the one two lines before, fix it>

[source, cypher, subs = attributes]
----
LOAD CSV WITH HEADERS FROM "{csv-url}allegiances.csv" AS row
MATCH (character:Character {id: row.character})
MATCH (house:House {id: row.houseLink})
RETURN character, house, row.houseName
----

These are the current allegiances:

[source, cypher, subs = attributes]
----
LOAD CSV WITH HEADERS FROM "{csv-file}allegiances.csv" AS row
WITH row WHERE (NOT tolower(row.houseName) CONTAINS "former") AND (NOT tolower(row.houseName) CONTAINS "until")
MATCH (character:Character {id: row.character})
MATCH (house:House {id: row.houseLink})
RETURN character, house, row.houseName
----

Let's create previous allegiances as well:

[source, cypher, subs = attributes]
----
LOAD CSV WITH HEADERS FROM "{csv-file}allegiances.csv" AS row
WITH row WHERE tolower(row.houseName) CONTAINS "former" OR tolower(row.houseName) CONTAINS "until"
MATCH (character:Character {id: row.character})
MATCH (house:House {id: row.houseLink})
MERGE (character)-[:PREVIOUSLY_HAD_ALLEGIANCE_TO]->(house)
----
